language: objective-c

notifications:
  email:
    on_success: never
    on_failure: never

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

branches:
  only:
    - spec

env:
  - APM_TEST_PACKAGES="language-agda"
